### PR TITLE
fix example

### PR DESCRIPTION
**Pull request by dcharbonnier**

### CODE REVIEW

**Comment by dustinnewman** [comment]
Thank you for this! It's been throwing ECONNREFUSED for the past hour!! Had to dive into the source to figure out why.

**Comment by ashconnell** [comment]
This should really be merged... :/

**Comment by curran** [comment]
Agreed. /cc @nateps

**Comment by rajan123456** [comment]
+1, please merge

**Comment by nateps** [comment]
Thanks!

**Pull request merged**
