### PR TITLE
Basic project documentation

### LINKED ISSUE #3: Basic project documentation
I'm looking into ShareDB and it is not clear what the function of this project is. It would be good to have documentation which includes things like:
- What is the pub/sub system which this library is built for?
- Why would you use this Redis library over the default memory one?
- Are there any disadvantages of using this library?

### PR DESCRIPTION
**Pull request by curran**
Closes #3

Related to https://github.com/share/sharedb/issues/158

### CODE REVIEW

**Comment by curran** [comment]
Requesting review from @bradisbell . Is this clear? Any information missing? Thanks!

**Comment by bradisbell** [comment]
Thanks @curran .  I think it's clear for the general use case.  What I'm trying to do is maintain state between Node.js instances only.  (There might be a web-based client for a status page or something, but really what I want is a shared object among Node.js servers.  It seems like all the operational transform machinery is in place with ShareDB... I'm just trying to use it in a way where servers keep each other updated.)  It isn't clear if that's possible or not, but admittedly I'm just coming across this repo for the first time.

**Comment by curran** [comment]
@nateps @josephg @avital This PR is ready for review and merge.

**Comment by curran** [comment]
Can anyone review this PR?

**Review by rkstedman — APPROVED** [review]

**Comment by curran** [comment]
@rkstedman Thanks so much!

**Pull request merged**
